// Builds every icon asset from the owner's mark (branding/logo-mono.svg, paths untouched).
// Outputs: colour mark variants, app-icon tiles, tray/symbolic glyphs, PNG renders, Store tiles,
// Flathub icons, and finally runs `tauri icon` for the platform bundles.
//
//   node scripts/build-icons.ts            (Node >= 22.13, uses type stripping)
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { Resvg } from '@resvg/resvg-js';

const root = join(import.meta.dirname, '..');
const p = (...parts: string[]) => join(root, ...parts);

const mono = readFileSync(p('branding/logo-mono.svg'), 'utf8');
const paths = [...mono.matchAll(/<path d="([^"]+)"\/>/g)].map((m) => m[1]);
if (paths.length !== 4) throw new Error(`Expected 4 paths in logo-mono.svg, found ${paths.length}`);
const [DOME, BOOK, DOOR, MOON] = paths;

type Stop = [number, string];
const grad = (id: string, stops: Stop[], x1 = 0.18, y1 = 0, x2 = 0.82, y2 = 1) =>
  `<linearGradient id="${id}" x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}">` +
  stops.map(([o, c]) => `<stop offset="${o}" stop-color="${c}"/>`).join('') +
  `</linearGradient>`;

interface Palette {
  dome: Stop[];
  door: Stop[];
  book: Stop[];
  moon: Stop[];
}

const PALETTE_LIGHT_UI: Palette = {
  dome: [
    [0, '#A9C3AC'],
    [0.45, '#6E9179'],
    [1, '#34543F'],
  ],
  door: [
    [0, '#F6E7BE'],
    [0.55, '#E0C07F'],
    [1, '#B98D4B'],
  ],
  book: [
    [0, '#A9844C'],
    [0.5, '#E7D3A0'],
    [1, '#A9844C'],
  ],
  moon: [
    [0, '#F3E2B3'],
    [1, '#BE924F'],
  ],
};

const PALETTE_DARK_UI: Palette = {
  ...PALETTE_LIGHT_UI,
  dome: [
    [0, '#F6F1E3'],
    [0.5, '#D2DDCB'],
    [1, '#98B19D'],
  ],
};

function markDefs(prefix: string, pal: Palette) {
  return (
    grad(`${prefix}-dome`, pal.dome) +
    grad(`${prefix}-door`, pal.door, 0.5, 0, 0.5, 1) +
    grad(`${prefix}-book`, pal.book, 0, 0.5, 1, 0.5) +
    grad(`${prefix}-moon`, pal.moon, 0, 0, 1, 1)
  );
}

function markPaths(prefix: string) {
  return [
    `<path fill="url(#${prefix}-dome)" d="${DOME}"/>`,
    `<path fill="url(#${prefix}-book)" d="${BOOK}"/>`,
    `<path fill="url(#${prefix}-door)" d="${DOOR}"/>`,
    `<path fill="url(#${prefix}-moon)" d="${MOON}"/>`,
  ].join('\n  ');
}

const SVG_ATTRS = 'style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2"';

function colourMark(pal: Palette, note: string) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Ahd mark, ${note}. Paths are the owner's original mark (branding/logo-mono.svg), unchanged;
     only the fills are gradients. Generated by scripts/build-icons.ts. -->
<svg width="153" height="207" viewBox="0 0 153 207" xmlns="http://www.w3.org/2000/svg" ${SVG_ATTRS}>
  <title>Ahd</title>
  <defs>${markDefs('ahd', pal)}</defs>
  ${markPaths('ahd')}
</svg>
`;
}

function monoMark(fill: string, note: string) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Ahd mark, ${note}. Generated by scripts/build-icons.ts. -->
<svg width="153" height="207" viewBox="0 0 153 207" xmlns="http://www.w3.org/2000/svg" ${SVG_ATTRS}>
  <g fill="${fill}">${paths.map((d) => `<path d="${d}"/>`).join('')}</g>
</svg>
`;
}

// Square glyph (for tray / symbolic): mark centred in a square viewBox, height-fitted.
function squareGlyph(fill: string, size = 207, pad = 6) {
  const scale = (size - pad * 2) / 207;
  const w = 153 * scale;
  const tx = (size - w) / 2;
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${size}" height="${size}" viewBox="0 0 ${size} ${size}" xmlns="http://www.w3.org/2000/svg" ${SVG_ATTRS}>
  <g fill="${fill}" transform="translate(${tx.toFixed(3)} ${pad}) scale(${scale.toFixed(5)})">${paths
    .map((d) => `<path d="${d}"/>`)
    .join('')}</g>
</svg>
`;
}

function appTile(opts: {
  bg: Stop[];
  pal: Palette;
  patternColour: string;
  patternOpacity: number;
  shadowOpacity: number;
  rounded?: boolean;
  markHeight?: number;
}) {
  const S = 1024;
  const s = (S * (opts.markHeight ?? 0.68)) / 207;
  const w = 153 * s;
  const h = 207 * s;
  const tx = (S - w) / 2;
  const ty = (S - h) / 2 + 4;
  const rx = opts.rounded === false ? 0 : 232;
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Ahd app icon. Generated by scripts/build-icons.ts from branding/logo-mono.svg. -->
<svg width="${S}" height="${S}" viewBox="0 0 ${S} ${S}" xmlns="http://www.w3.org/2000/svg">
<title>Ahd</title>
<defs>
${grad('bg', opts.bg, 0.15, 0, 0.85, 1)}
${markDefs('ahd', opts.pal)}
<pattern id="khatam" width="128" height="128" patternUnits="userSpaceOnUse"><g fill="none" stroke="${opts.patternColour}" stroke-width="2.5" opacity="${opts.patternOpacity}"><rect x="37" y="37" width="54" height="54"/><rect x="37" y="37" width="54" height="54" transform="rotate(45 64 64)"/></g></pattern>
<radialGradient id="glow" cx="0.5" cy="0.6" r="0.55"><stop offset="0" stop-color="#F6E7BE" stop-opacity="0.20"/><stop offset="1" stop-color="#F6E7BE" stop-opacity="0"/></radialGradient>
<filter id="sh" x="-25%" y="-25%" width="150%" height="150%"><feGaussianBlur in="SourceAlpha" stdDeviation="5"/><feOffset dx="0" dy="4" result="b"/><feFlood flood-color="#08110B" flood-opacity="${opts.shadowOpacity}"/><feComposite in2="b" operator="in"/><feMerge><feMergeNode/><feMergeNode in="SourceGraphic"/></feMerge></filter>
<clipPath id="sq"><rect x="0" y="0" width="${S}" height="${S}" rx="${rx}" ry="${rx}"/></clipPath>
</defs>
<g clip-path="url(#sq)">
<rect width="${S}" height="${S}" fill="url(#bg)"/>
<rect width="${S}" height="${S}" fill="url(#khatam)"/>
<rect width="${S}" height="${S}" fill="url(#glow)"/>
</g>
<g transform="translate(${tx.toFixed(2)} ${ty.toFixed(2)}) scale(${s.toFixed(5)})" filter="url(#sh)" ${SVG_ATTRS}>
  ${markPaths('ahd')}
</g>
</svg>
`;
}

function wideTile(width: number, height: number, bg: Stop[], pal: Palette) {
  const mh = height * 0.62;
  const s = mh / 207;
  const tx = (width - 153 * s) / 2;
  const ty = (height - mh) / 2;
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" xmlns="http://www.w3.org/2000/svg">
<defs>${grad('bg', bg, 0.15, 0, 0.85, 1)}${markDefs('ahd', pal)}</defs>
<rect width="${width}" height="${height}" fill="url(#bg)"/>
<g transform="translate(${tx.toFixed(2)} ${ty.toFixed(2)}) scale(${s.toFixed(5)})" ${SVG_ATTRS}>${markPaths('ahd')}</g>
</svg>
`;
}

function render(svg: string, out: string, width: number) {
  const png = new Resvg(svg, { fitTo: { mode: 'width', value: width }, background: 'rgba(0,0,0,0)' })
    .render()
    .asPng();
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, png);
}

function save(rel: string, content: string) {
  mkdirSync(dirname(p(rel)), { recursive: true });
  writeFileSync(p(rel), content);
}

// ---- colour marks
const logo = colourMark(PALETTE_LIGHT_UI, 'colour edition for light backgrounds');
const logoDark = colourMark(PALETTE_DARK_UI, 'colour edition for dark backgrounds');
save('branding/logo.svg', logo);
save('branding/logo-dark.svg', logoDark);
// in-app copies (imported by the UI)
save('src/design/brand/logo.svg', logo);
save('src/design/brand/logo-dark.svg', logoDark);

// ---- app tiles
const BG_DARK: Stop[] = [
  [0, '#35523F'],
  [0.55, '#233829'],
  [1, '#131F17'],
];
const BG_LIGHT: Stop[] = [
  [0, '#F8F4EA'],
  [1, '#E4DAC3'],
];
const appIcon = appTile({ bg: BG_DARK, pal: PALETTE_DARK_UI, patternColour: '#F4EEDD', patternOpacity: 0.07, shadowOpacity: 0.45 });
const appIconLight = appTile({ bg: BG_LIGHT, pal: PALETTE_LIGHT_UI, patternColour: '#4E6754', patternOpacity: 0.06, shadowOpacity: 0.18 });
save('branding/app-icon.svg', appIcon);
save('branding/app-icon-light.svg', appIconLight);
render(appIcon, p('branding/png/app-icon-1024.png'), 1024);
render(appIconLight, p('branding/png/app-icon-light-1024.png'), 1024);
render(logo, p('branding/png/logo-512.png'), 512);

// ---- monochrome glyphs (tray, notifications, symbolic)
save('branding/tray/tray-light.svg', squareGlyph('#F4F1EA')); // for dark taskbars / panels
save('branding/tray/tray-dark.svg', squareGlyph('#1E2621')); // for light taskbars / panels
save('branding/tray/ahd-symbolic.svg', squareGlyph('#bebebe', 16 * 12, 6));
for (const size of [16, 20, 24, 32, 48, 64]) {
  render(squareGlyph('#F4F1EA'), p(`src-tauri/icons/tray/tray-light-${size}.png`), size);
  render(squareGlyph('#1E2621'), p(`src-tauri/icons/tray/tray-dark-${size}.png`), size);
}
render(squareGlyph('#FFFFFF'), p('src-tauri/icons/notification-glyph-96.png'), 96);

// ---- Flathub / freedesktop
save('packaging/flatpak/icons/scalable/io.github.ahdapp.Ahd.svg', appIcon);
save('packaging/flatpak/icons/symbolic/io.github.ahdapp.Ahd-symbolic.svg', squareGlyph('#bebebe', 16 * 12, 6));
for (const size of [128, 256, 512]) {
  render(appIcon, p(`packaging/flatpak/icons/${size}x${size}/io.github.ahdapp.Ahd.png`), size);
}

// ---- Microsoft Store wide tile + splash (square tiles come from `tauri icon`)
render(wideTile(620, 300, BG_DARK, PALETTE_DARK_UI), p('packaging/msix/Assets/Wide310x150Logo.scale-200.png'), 620);
render(wideTile(1240, 600, BG_DARK, PALETTE_DARK_UI), p('packaging/msix/Assets/SplashScreen.scale-200.png'), 1240);

// ---- platform bundles via the Tauri CLI
execFileSync(
  process.platform === 'win32' ? 'npx.cmd' : 'npx',
  ['tauri', 'icon', p('branding/png/app-icon-1024.png'), '-o', p('src-tauri/icons')],
  { stdio: 'inherit', cwd: root },
);
for (const f of ['Square44x44Logo.png', 'Square71x71Logo.png', 'Square150x150Logo.png', 'Square310x310Logo.png', 'StoreLogo.png']) {
  copyFileSync(p('src-tauri/icons', f), p('packaging/msix/Assets', f));
}
console.log('icons: done');
